name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: 
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
        
    - name: set release date
      run: echo "RELEASE_TIME=$(date +%s)" >> ${GITHUB_ENV}
        
    - name: test variable
      run: echo $RELEASE_TIME

    - name: Build Docker Image
      run: docker build . --file TicTacToeBackend/Dockerfile --tag ${{secrets.DOCKER_USER}}/tictactoebackend:$RELEASE_TIME
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/tictactoebackend:$RELEASE_TIME
